census_key: CENSUS_KEY
data_dir: data
output_dir: output
county_ids: [53033, 53035, 53053, 53061]
county_map:
  King County: 53033
  Kitsap County: 53035
  Pierce County: 53053
  Snohomish County: 53061
state_id: 53

headship_rates:
  - year: 2000
    column_name: headship_rate_2000
    filename: headship_rates_by_age.csv
  - year: 2010
    column_name: headship_rate_2010
    filename: headship_rates_by_age.csv
  - year: 2020
    column_name: headship_rate_2020
    filename: headship_rates_by_age.csv
  - year: 2024
    column_name: rolling_avg
    filename: pums_1yr_headship_rates_2024_by_county.csv

remi_forecast_dir: J:/Projects/Forecasts/_Regional/2026/REMI
remi_forecasts:
  - name: REMI_Adj_Base_to_OFM_2024hr
    filename: REMI_base_adj_to_OFM.xlsx
    headship_rate_year: 2024
  - name: REMI_Adj_Base_to_OFM_2020hr
    filename: REMI_base_adj_to_OFM.xlsx
    headship_rate_year: 2020
  - name: REMI_Adj_Base_to_OFM_2010hr
    filename: REMI_base_adj_to_OFM.xlsx
    headship_rate_year: 2010
  - name: REMI_Adj_Base_to_OFM_2000hr
    filename: REMI_base_adj_to_OFM.xlsx
    headship_rate_year: 2000
  # - name: OFM_v2022_High
  #   filename: REMI_OFM_v2022_High.xlsx
  # - name: OFM_v2022_Low
  #   filename: REMI_OFM_v2022_Low.xlsx
  - name: OFM_v2022_Med
    filename: REMI_OFM_v2022_Medium.xlsx
  - name: REMI_v3.3
    filename: REMI_v3.3.xlsx
  # - name: REMI_Scenario_Zero_Intl_Mig
  #   filename: REMI_v3.3_zero_intl_migration.xlsx
  # - name: REMI_Scenario_Amzn_+50%
  #   filename: REMI_v3.3_amzn_grows_50_pct.xlsx

prev_ofm_forcasts:
  - release_year: 2017
    projection_start_year: 2015
    filename: gma_2017_pop_med.xlsx
  - release_year: 2012
    projection_start_year: 2010
    filename: gma2012_1yr_med.xls
  - release_year: 2007
    projection_start_year: 2005
    filename: gma2007_1yr_med.xls
  - release_year: 2002
    projection_start_year: 2000
    filename: gma2002_med.xls

remi_output_file: REMI_forecasts_counties_summed_all_years.csv
remi_base_year: 2023
remi_history_file: REMI_History.xlsx
headship_rate_year: 2020

luvit_forecast_file: luvit.csv

pep_population_file: co-est2025-pop-53.xlsx
pep_housing_file: CO-EST2025-HU-53.xlsx

ofm_population_file: ofm_april1_postcensal_estimates_pop_1960-present.xlsx
ofm_housing_file: ofm_april1_postcensal_estimates_housing_1980_1990-present.xlsx

growth_targets:
  - name: growth_targets_v2026
    filename: extrapolated_targets2026.csv
    base_year: 2023
    target_year: 2044
    base_type: ofm
  - name: growth_targets_v2021
    filename: extrapolated_targets2021.csv
    base_year: 2020
    target_year: 2044
    base_type: dec

woods_poole_forecast_dir: J:/Projects/Forecasts/_Regional/2026/WoodsPoole
woods_poole_files:
  - 53033: King2026.csv
  - 53035: Kitsap2026.csv
  - 53053: Pierce2026.csv
  - 53061: Snohomish2026.csv

bayes_pop_file: bayes_pop_forecast.csv

steps:
  - macro_explorer.steps.get_decennial_data
  - macro_explorer.steps.get_acs_data
  - macro_explorer.steps.get_remi_hh_units
  # - macro_explorer.steps.render_dashboard
